global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
  - 'prometheus.rules.yml'
  
scrape_configs:
  - job_name: 'oracledb_exporter'
    static_configs:
      - targets: ['host.docker.internal:9161']